### PR TITLE
Upgrade to .NET 9 and entity framework 9

### PR DESCRIPTION
**Pull request by phenixdotnet**
Hi.

Not sure how you handle major version upgrade but if it can help you will find here a PR bumping .NET & entity framework version to 9.

No code change seem to be required and unit tests pass

### CODE REVIEW

**Review by MirolimMajidov — APPROVED** [review]

**Comment by ErikEJ** [comment]
.NET version should stay at 8.0

**Comment by phenixdotnet** [comment]
Hello @ErikEJ 

The package `Microsoft.EntityFrameworkCore.Specification.Tests` isn't compatible with .NET 8 so what do you prefere :
- Upgrade test project to .NET 9
- Downgrade the `Microsoft.EntityFrameworkCore.Specification.Tests` to `8.0.11` ?

Also I upgrade the major version of the project to `9.0.0` as changing the .NET version is a IMO a breaking change but if the .NET version is kept to .NET 8 is that still revelant ?

**Comment by phenixdotnet** [comment]
done :)

**Comment by attilah** [comment]
Please push the button @ErikEJ or @MirolimMajidov :) Thx for the PR @phenixdotnet!

**Comment by roji** [comment]
@attilah just to set expectations, I'm probably going to want to do a pass over pending issues and generally make sure everything looks good - actually publishing this plugin will take a bit more time.

**Review by roji — APPROVED** [review]

**Comment by roji** [comment]
FYI the build is failing since the Github Actions workflow is still using dotnet SDK 8. Will push a fix.

**Comment by attilah** [comment]
@roji understood, it is just a blocker for upgrading to .NET 9.0 as 8.0.3 has a <9.0 constraint on the ef core dependency, will monitor and upgrade once it is release!

**Pull request merged**
